baseURL = 'https://jayrovacsek.github.io/ncsg-presentation-august-2024/#/'
languageCode = 'en-au'
title = 'ncsg-presentation-august-2024'
theme = "github.com/dzello/reveal-hugo"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params.reveal_hugo]
theme = "league"
slide_number = true
transition_speed = 'fast'

[markup.goldmark.extensions.extras.superscript]
enable = true
